[package]
name = "snake-piston"
version = "0.0.1"
authors = ["Alexandru Cojocaru <xojoc@gmx.com>"]

[[bin]]
name = "snake"
path = "snake.rs"

[dependencies]
piston = "0.1.5"
pistoncore-glutin_window = "0.2.0"
piston2d-graphics = "0.1.4"
piston2d-opengl_graphics = "0.1.0"
rand = "0.3"